const projects = [
    {
        id: 'radiocast',
        title: 'RadioCast',
        type: 'app',
        coverImage: '../assets/images/Radiocast/Radiocast-Cover.jpg',
        coverBg: 'bg-white',
        role: 'UI/UX Designer',
        year: '2026',
        client: 'SBXone',
        creator: 'Dyven Siauw',
        liveUrl: null,
        overview: [
            'Radiocast adalah sebuah aplikasi pemutar radio streaming yang dirancang untuk memberikan pengalaman mendengarkan radio yang modern dan intuitif.',
            'Project ini berfokus pada kemudahan navigasi dan tampilan yang bersih, memungkinkan pengguna untuk menemukan dan mendengarkan stasiun radio favorit mereka dengan cepat.',
        ],
        mockup: ['../assets/images/Radiocast/Mockup/Radiocast-Cover-1.webp', '../assets/images/Radiocast/Mockup/Radiocast-Cover-2.webp', '../assets/images/Radiocast/Mockup/Radiocast-Cover-3.webp', '../assets/images/Radiocast/Mockup/Radiocast-Cover-4.webp'],
        screen: ['../assets/images/Radiocast/Screen/Radiocast-onboard.webp', '../assets/images/Radiocast/Screen/Radiocast-home.webp', '../assets/images/Radiocast/Screen/Radiocast-podcastSearch.webp', '../assets/images/Radiocast/Screen/Radiocast-podcastList.webp', '../assets/images/Radiocast/Screen/Radiocast-podcastPlay.webp', '../assets/images/Radiocast/Screen/Radiocast-podcastDesc.webp'],
    },

    {
        id: 'zero',
        title: 'Zero',
        type: 'app',
        coverImage: '../assets/images/',
        coverBg: 'bg-white',
        role: 'UI/UX Designer',
        year: '2026',
        client: 'SBXone',
        creator: 'Dyven Siauw',
        liveUrl: null,
        overview: [
            'Zero adalah sebuah aplikasi perbankan yang dirancang dengan tampilan yang modern, intuitif dan simpel. Memastikan setiap komponen memiliki peran visual masing-masing demi menghindari misnavigation dam cognitive overload yang biasa terjadi pada aplikasi perbankan serupa.',
            'Desain berfokus pada pengalaman pengguna yang tenang dan bebas gangguan, dengan fitur kategorisasi uang yang membantu pengguna dalam menyisihkan uang mereka.',
        ],
        mockup: ['../assets/images/Zero/Mockup/Zero-Cover-1.webp', '../assets/images/Zero/Mockup/Zero-Cover-2.webp', '../assets/images/Zero/Mockup/Zero-Cover-3.webp', '../assets/images/Zero/Mockup/Zero-Cover-4.webp'],
        screen: ['../assets/images/Zero/Screen/Zero-splash.webp', '../assets/images/Zero/Screen/Zero-onboard.webp', '../assets/images/Zero/Screen/Zero-home.webp', '../assets/images/Zero/Screen/Zero-cardsDrag.webp', '../assets/images/Zero/Screen/Zero-cardsList.webp', '../assets/images/Zero/Screen/Zero-send.webp'],
    },

    {
        id: 'schedller',
        title: 'Schedller',
        type: 'app',
        coverImage: '../assets/images/',
        coverBg: 'bg-white',
        role: 'UI/UX Designer',
        year: '2026',
        client: 'SBXone',
        creator: 'Dyven Siauw',
        liveUrl: null,
        overview: [
            'Schedller adalah sebuah aplikasi manajemen tugas yang dirancang untuk membantu pengguna mengorganisir tugas mereka secara visual.',
            'Dengan mengutamakan hirarki visual sebagai komponen utama, Schedller tidak hanya memastikan pengguna dapat mengelola tugas mereka dengan mudah dan efisien, namun juga dapat membaca jadwal dengan mudah.',
        ],
        mockup: ['../assets/images/Schedller/Mockup/Schedller-Cover-1.webp', '../assets/images/Schedller/Mockup/Schedller-Cover-2.webp', '../assets/images/Schedller/Mockup/Schedller-Cover-3.webp', '../assets/images/Schedller/Mockup/Schedller-Cover-4.webp'],
        screen: ['../assets/images/Schedller/Screen/Schedller-splash.webp', '../assets/images/Schedller/Screen/Schedller-home.webp', '../assets/images/Schedller/Screen/Schedller-schedule.webp', '../assets/images/Schedller/Screen/Schedller-scheduleNew.webp', '../assets/images/Schedller/Screen/Schedller-profile.webp'],
    },

    {
        id: 'xpandable',
        title: 'Xpandable',
        type: 'app',
        coverImage: '../assets/images/Xpandable-Cover.jpg',
        coverBg: 'bg-black',
        role: 'UI/UX Designer & Front-end Developer',
        year: '2026',
        client: 'SBXone',
        creator: 'Dyven Siauw',
        liveUrl: null,
        overview: [
            'Xpandable adalah sebuah aplikasi manajemen keuangan yang dirancang untuk membantu pengguna mengelola keuangan mereka secara visual.',
            'Dengan menghadirkan fitur AI analytics, user tidak hanya dapat melihat grafik pengeluaran mereka, namun juga dapat berdiskusi dengan AI untuk mencari solusi agar pengeluaran mereka berkurang.',
        ],
        mockup: ['../assets/images/Xpandable/Mockup/Xpandable-Cover-1.webp', '../assets/images/Xpandable/Mockup/Xpandable-Cover-2.webp', '../assets/images/Xpandable/Mockup/Xpandable-Cover-3.webp', '../assets/images/Xpandable/Mockup/Xpandable-Cover-4.webp'],
        screen: ['../assets/images/Xpandable/Screen/XPandable-onboard.webp', '../assets/images/Xpandable/Screen/XPandable-home.webp', '../assets/images/Xpandable/Screen/XPandable-AIchat.webp', '../assets/images/Xpandable/Screen/XPandable-AIreply.webp', '../assets/images/Xpandable/Screen/XPandable-send.webp', '../assets/images/Xpandable/Screen/XPandable-expenses.webp', '../assets/images/Xpandable/Screen/XPandable-income.webp'],
    },
    {
        id: 'thinker',
        title: 'Thinker',
        type: 'website',
        coverImage: '../assets/images/Thinker-Cover.jpg',
        coverBg: 'bg-white',
        role: 'UI/UX Designer',
        year: '2026',
        client: 'SBXone',
        creator: 'Dyven Siauw',
        liveUrl: null,
        overview: [
            'Thinker adalah sebuah website agensi kreatif, dengan gaya visual yang unik namun tetap menjaga keseimbangan dan kerapihan setiap komponen.',
            'Project ini merupakan project pertama saya sebagai ui/ux designer di sbxone.',
        ],
        mockup: ['../assets/images/Thinker/Mockup/Thinker-Cover-1.webp', '../assets/images/Thinker/Mockup/Thinker-Cover-2.webp', '../assets/images/Thinker/Mockup/Thinker-Cover-3.webp', '../assets/images/Thinker/Mockup/Thinker-Cover-4.webp'],
        screen: ['../assets/images/Thinker/Screen/Thinker-Desktop.webp'],
    },
    {
        id: 'gjf',
        title: 'Global Journalist Federation',
        type: 'website',
        coverImage: '../assets/images/GJF-Cover.jpg',
        coverBg: 'bg-white',
        role: 'UI/UX Designer',
        year: '2026',
        client: 'SBXone',
        creator: 'Dyven Siauw',
        liveUrl: null,
        overview: [
            'Global Journalist Federation adalah sebuah website organisasi jurnalis internasional, dengan gaya visual modern namun tetap terasa profesional dan berwibawa.',
            'Dengan warna merah sebagai warna utama, website ini memberikan nuansa yang berani, tegas, dan penuh semangat, namun disisi lain warna merah juga melambangkan tragedi yang pernah terjadi kepada para jurnalis.',
        ],
        mockup: ['../assets/images/GJF/Mockup/GJF-Cover-1.webp', '../assets/images/GJF/Mockup/GJF-Cover-2.webp', '../assets/images/GJF/Mockup/GJF-Cover-3.webp', '../assets/images/GJF/Mockup/GJF-Cover-4.webp'],
        screen: ['../assets/images/GJF/Screen/GJF-desktop.webp'],
    },
];
